* This is my file



Practical sites:


I followed the steps of this site: https://streakycobra.github.io/posts/blogging-in-org-mode-with-nikola/

Other useful sites

- https://jiaweizhuang.github.io/blog/nikola-guide/
- https://www.frankliu.org/posts/setting-up-nikola-org-mode/

https://gist.github.com/redguardtoo

First install nikola
#+begin_src shell
pip install nikola
pip install aiohttp  # for nikola auto to work
pip install watchdog # for nikola auto to work
pip install ghp-import2 # for deploying to github
#+end_src


Then install the org mode plugin

#+begin_src shell
nikola plugin -i orgmode
#+end_src


Add this to =plugins/orgmode/init.el= to enable links to internal pages

#+begin_src emacs-lisp
(org-link-set-parameters
 "link"
 :export (lambda (path desc backend)
           (cond
            ((eq 'html backend)
             (format "<a href=\"link:%s\">%s</a>"
                     path (or desc path)))))
)
#+end_src


There was a problem with linking to the images. For this I had to change the following in the  =init.el= file.

#+begin_src emacs-lisp :tangle yes
;; Export images with built-in file scheme
(defun org-file-link-img-url-export (path desc format)
  (cond
   ((eq format 'html)
    (format "<img src=\"%s\" alt=\"%s\"/>" path desc)))) ;; This line
(org-add-link-type "file" nil 'org-file-link-img-url-export)
#+end_src

The main problem was in the line marked as  "This line". The line was like this:
#+begin_src emacs-lisp :tangle yes
(format "<img src=\"/%s\" alt=\"%s\"/>" path desc)))) ;; This line
#+end_src
Specically note the "/" in front of the first "/%s". This slash should  be removed.

Kijk naar deze code in the =homepage/plugins/orgmode/init.el=
#+begin_src emacs-lisp :tangle yes
;; Export images with custom link type
(defun org-custom-link-img-url-export (path desc format)
  (cond
   ((eq format 'html)
    (format "<img src=\"%s\" alt=\"%s\"/>" path desc))))
(org-add-link-type "img-url" nil 'org-custom-link-img-url-export)
#+end_src
Als je nu in een org file naar een figure/image verwijst met =img-url:/images/number_game.png=, dus met =img-url:= ervoor, dan werkt het wel. In de code hierboven kan je de =file:= gebruiken voor een figuur, maar met die =/= voor die =/%s= bevat de code een bug.


* compiling

#+begin_src shell
emacs --batch -l /home/nicky/Dropbox/homepage/plugins/orgmode/init.el --eval '(nikola-html-export "/home/nicky/Dropbox/homepage/posts/solving-a-number-game-with-a-mip-solver.org" "/home/nicky/Dropbox/homepage/cache/posts/solving-a-number-game-with-a-mip-solver.html")'
#+end_src


* Make a github io repo

Make an empty repo, no =readme= or -.gitignore=


#+begin_src shell
git clone https://github.com/ndvanforeest/ndvanforeest.github.io.git ~/homepage
cd homepage
git co -b src
nikola init my_site
#+end_src

Fill in the questions. My homepage is this: https://ndvanforeest.github.io/

#+begin_src shell
mv my_site/* .
rm -rf my_site/

git add README.org
#+end_src



* Making new posts


#+begin_src shell
nikola new_post -f orgmode -t "Solving a number game with a MIP solver"
#+end_src

#+RESULTS:
| Creating          | New     | Post |        |      |      |   |     |        |
| ----------------- |         |      |        |      |      |   |     |        |
|                   |         |      |        |      |      |   |     |        |
| Title:            | Solving | a    | number | game | with | a | MIP | solver |

It seems that when updating files that are symlinks, that =nikola= does not quite get the updates.


* Test locally

#+begin_src shell
nikola auto
#+end_src




* Making new pages

#+begin_src shell
nikola new_page -f orgmode -t "bio"
#+end_src

#+RESULTS:
| Creating          | New | Page |
| ----------------- |     |      |
|                   |     |      |
| Title:            | bio |      |


* Upload to github

Stay in the =src= branch! Don't commmit. The following handles all.

#+begin_src shell
cd /home/nicky/Dropbox/homepage/
nikola github_deploy
#+end_src

Clean up:

#+begin_src shell
cd /home/nicky/Dropbox/homepage/
nikola check --clean-files
#+end_src

#+RESULTS:

* Css stuff

Dit is de inhoud van een custom.css file die ik vond. Het is mss een handig voorbeeld.

/* BLOCKS */
#content .special-block {
  padding: 12px;
  line-height: 24px;
  margin-bottom: 24px;
}
#content .special-block p:last-child {
  margin-bottom: 0;
}
#content .admonition-title {
  color: #fff;
  font-weight: bold;
  display: block;
  padding: 6px 12px;
  margin-bottom: 0px;
}
/* Definition: green */
#content .definition {background-color: #dbfaf4;}
#content p.admonition-title.definition {background-color: #1abc9c;}
/* Theorem: orange */
#content .theorem,
#content .postulate,
#content .axiom,
#content .corollary,
#content .lemma {background-color: #ffedcc;}
#content p.admonition-title.theorem,
#content p.admonition-title.postulate,
#content p.admonition-title.axiom,
#content p.admonition-title.corollary,
#content p.admonition-title.lemma {background-color: #f0b37e;}
/* Proposition: blue*/
#content .proposition,
#content .principia {background-color: #e7f2fa;}
#content p.admonition-title.proposition,
#content p.admonition-title.principia{background-color: #6ab0de;}
/* Algorithm: gray */
#content .alg {background-color: #ddd;}
#content p.admonition-title.alg {background-color: #333;}

#content .theorem{ display:block;    margin-left:10px;    margin-bottom:20px;    font-style:normal;}
#content .theorem:before{ content:"Theorem.\00a0\00a0"; float:left; font-weight:bold; }
