#+BEGIN_COMMENT
.. title: latex-pythontex-matplotlib-tikzplotlib
.. slug: latex-pythontex-matplotlib-tikzplotlib
.. date: 2020-09-30 21:18:52 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* The  problem

Sometimes I want to use a python script to produce a plot and include this plot in LaTeX.
My usual approach was like this.
First I wrote a python script that at the end exported the plot to a pdf file.
Then I imported the pdf file within a figure environment in a LaTeX file.
Thus, I had three files, of which two were kind of superfluous.
And, after some time, I typically forgot which python I used to make the pdf file, so I included comments in my LaTeX file to explain where to find what. 

* My solution
And then there came a day that I did not like this anymore.
I wanted one file that does all, provided it takes not a lot of time to make the data for the graphs.
After some searching and testing, here is an MWE of how I am doing things now with =pythontex=, =matplotlib= and =tikzplotlib=.  I use =arara= to compile the LaTeX file, but this just handy, not necessary for the rest to work. 

** Without the code in the LaTeX file

If you want to run the code, but don't want to show it, use the =pycode= environment.

#+BEGIN_SRC latex
% arara: pdflatex: { shell: yes }
% arara: pythontex: {verbose: yes, rerun: modified }
% arara: pdflatex: { shell: yes }

\documentclass{article}
\usepackage{pythontex}
\usepackage{pgfplots}

\title{Example graph}
\author{Nicky}
\begin{document}
\maketitle

If you want to run the code, but don't want to show it, use the \verb+pycode+ environment.

\begin{figure}[h]
\centering
\begin{pycode}

from matplotlib.pylab import plt
import tikzplotlib

plt.plot([1, 2, 3], [1, 5, 2], label="x")

plt.legend()
print(tikzplotlib.get_tikz_code(axis_height="5cm", axis_width="6cm"))
\end{pycode}
\caption{It works.}
\end{figure}
\end{document}
#+END_SRC

** With the code in the LaTeX file

If you like to include the code to show how you made the graph, use the =pyblock= environment, and then =\printpythontex= within a figure environment.

#+BEGIN_SRC latex
% arara: pdflatex: { shell: yes }
% arara: pythontex: {verbose: yes, rerun: modified }
% arara: pdflatex: { shell: yes }

\begin{document}
\maketitle

If you like to include the code to show how you made the graph, use the \verb+pyblock+ environment, and then use \verb+\printpythontex+ within a figure environment.
Like this:

\begin{pyblock}

from matplotlib.pylab import plt
import tikzplotlib

plt.plot([1, 2, 3], [9, -1, 8], label="x")

plt.legend()
print(tikzplotlib.get_tikz_code(axis_height="5cm", axis_width="6cm"))
\end{pyblock}

\begin{figure}[h]
  \centering
  \printpythontex
\end{figure}

\end{document}
#+END_SRC

