#+BEGIN_COMMENT
.. title: latex-pythontex-matplotlib-tikzplotlib
.. slug: latex-pythontex-matplotlib-tikzplotlib
.. date: 2020-09-30 21:18:52 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

Sometimes I want to use a python script to produce a plot and include this plot in LaTeX.
My usual approach was like this.
First I wrote a python script that at the end exported the plot to a pdf file.
Then I imported the pdf file within a figure environment in a LaTeX file.
Thus, I had three files, of which two were kind of superfluous.
And, after some time, I typically forgot which python I used to make the pdf file, so I included comments in my LaTeX file to explain where to find what. 

And then there came a day that I did not like this anymore.
I wanted one file that does all, provided it takes not a lot of time to make the data for the graphs.
After some searching and testing, here is an MWE of how I am doing things now with =pythontex=, =matplotlib= and =tikzplotlib=.  I use =arara= to compile the LaTeX file, but this just handy, not necessary for the rest to work. 

#+BEGIN_SRC latex
% arara: pdflatex: { shell: yes, interaction: nonstopmode }
% arara: pythontex: {verbose: yes, rerun: modified }
% arara: pdflatex: { shell: yes, interaction: nonstopmode }

\documentclass{article}
\usepackage{pythontex}
\usepackage{pgfplots}

\title{Example graph}
\author{Nicky}
\begin{document}
\maketitle

\begin{figure}[h]
\centering
\begin{pycode}

from matplotlib.pylab import plt
import tikzplotlib

plt.plot([1, 2, 3], [1, 5, 2], label="x")

plt.legend()
print(tikzplotlib.get_tikz_code(axis_height="5cm", axis_width="6cm"))
\end{pycode}
\caption{It works.}
\end{figure}

\end{document}
#+END_SRC
