#+BEGIN_COMMENT
.. title: Bio
.. slug: Bio
.. date: 2020-09-30 21:42:32 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT

* Resume

Nicky van Foreest studied [[http://web.science.uu.nl/ITF/][Theoretical Physics]] at [[http://www.uu.nl][Utrecht University]], the Netherlands.
After having worked for several years at KPN Research, and the Bell Labs department of Lucent Technologies in Enschede, he started a PhD project under supervision of 
[[http://homepages.cwi.nl/~michel/][Michel Mandjes]] and [[http://www.math.utwente.nl/~scheinhardtwrw/][Werner Scheinhardt]] in 2000.
After the successful defence of his thesis in 2004 he joined [[http://www.quintiq.com][Quintiq]] to work on advanced planning, scheduling and supply chain optimization software.
Since 2006 he works at the [[http://www.rug.nl/feb][Faculty of Economics and Business]] of the [[http://www.rug.nl][University of Groningen]].
His main interests are in performance analysis and optimal control of stochastic logistic systems.


* Research Interests

Applications of probability and optimization to improve manufacturing, inventory, queueing, and service processes.

* Personal

Married to [[http://sheila.vanforeest.com/index.html][Sheila Timp]] and I have six children, whose homepages can be found [[http://vanforeest.com][here]].

* Where to find me
 
| Dr. N.D. van Foreest | Faculty of Economics and Business, University of Groningen |
| Visiting address:    | Room Duisenberg 666, Nettelbosje 2, 9747 AE Groningen            |
| Postal address:      | P.O.Box 800, 9700 AV,  Groningen, The Netherlands                |
| Tel:                 | +31-50 36 35178/37020                                            |
| Email:               | N.D.van.Foreest@rug.nl                                           |
| Github:              | [[https://github.com/ndvanforeest][ndvanforeest]]                                                     |
| Work Homepage:       | [[https://www.rug.nl/staff/n.d.van.foreest/][N.D. van Foreest]]                                                 |

