#+BEGIN_COMMENT
.. title: Tools
.. slug: tools
.. date: 2020-09-30 21:42:32 UTC+02:00
.. tags:
.. category:
.. link:
.. description:
.. type: text
.. has_math: true

#+END_COMMENT


* My Favorite Software Tools

- [[https://www.gnu.org/software/emacs/][Emacs editor]].  My =init.el= file is on [[https://github.com/ndvanforeest/emacs][github]].
- [[https://manjaro.org/][Manjaro linux]]
- [[https://i3wm.org/][i3 window manager]]
- [[https://www.python.org/][python]], [[https://numpy.org][numpy]], [[https://scipy.org][scipy]]
- [[https://www.latex-project.org/][$\LaTeX$]]
- [[https://orgmode.org/][orgmode]] for keeping notes,
- [[https://orgmode.org/worg/org-contrib/babel/][Org babel]] for literate programming.
- [[https://github.com/ndvanforeest][github]]
- [[https://github.com/gpoore/pythontex][pythontex]] to include python code in $\LaTeX$, although I am using org babel more and more for this.
- [[https://github.com/asottile/blacken-docs][blacken-docs]] formats python code in python scripts, but also in, for instance, $\LaTeX$ files.
- [[https://github.com/cereda/arara][arara]] to control the compilation process of $\LaTeX$ files


- I tended to use [[https://pypi.org/project/ipynb-py-convert/][ipynb-py-convert]] to convert between =.py= and =.ipynb= (jupiter notebook) files.
  This is practical when you don't like to use the notebook editor.
  In my case, I write a python file in emacs.
  Then, with adding the minor formatting string =# %%= to delineate the cells, this tool converts the python file to a jupyter notebook file.
  However,  orgmode is so much better that I will not use notebooks any time soon.


** Youtube videos

- =uxplay= to mirror my ipad so that I can write on my ipad, with an apple pencil, and have the notes shown on my computer screen (which I can then share with google meet for instance)
- =qvidcap= for screen capturing. I used =cheese= before but =qvidcap= is pre-installed on manjaro.
- =kazam= to make youtube movies. Before =kazam= I tried ~simplescreenrecorder~, but this froze my screen a few times.
- =qvlc= (or =vlc=) to play video. =parole= is pre-installed on manjaro linux, but it crashes on my machine.

- Perhaps this is a useful tool for screenrecording: https://obsproject.com/

- =pinta= for on screen drawing. However, now I write on my ipad with an apple pen and share the screen of the ipad via =uxplay=. The apple pen works amazingly  well on the ipad; I am very satisfied with this actually. (Earlier I use  a wacom device and ~xournal~ to write  and draw, but I found is very unpractical to only see on the computer screen what I was writing.)




* Building this site

I built this site with [[https://getnikola.com/][Nikola]], a site generator that I chose for three reasons:

1. I want to write pages and posts in org format and plain and simple $\LaTeX$. (I find writing maths in restructured text abhorrant.)
2. I don't want to use yet another programming language, python suffices for nearly all my goals, and Nikola is written in python.
2. I want to deploy my site on [[https://pages.github.com/][github pages]]. With nikola it's super easy to achieve that.
